site_name: OpenShock
docs_dir: docs
site_url: https://openshock.io/
repo_url: https://github.com/Shock-Link/Wiki

nav:
  - Home: index.md
  - Quickstart:
    - quickstart/welcome.md
    - quickstart/select-server.md
    - quickstart/create-account.md
    - quickstart/add-shockers.md
  - Hardware:
    - 'hardware/buy.md'
    - 'hardware/assembly.md'
    - Pishock:
      - 'hardware/pishock/index.md'
      - 'hardware/pishock/custom-v1.md'
  - Selfhosting:
    - 'selfhosting/selfhosting.md'
  - Contributing:
    - 'contributing/contributing.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags:
      enabled: true
      
extra:
  # Tag definitions for tagging pages.
  tags:
    selfhosting: banana

  # Social links rendered in the footer.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord,gg/AHcCbXbEcF
      name: Discord

    - icon: fontawesome/brands/github
      link: https://github.com/Shock-Link
      name: GitHub
