site_name: OpenShock
docs_dir: docs
site_url: https://openshock.io/
repo_url: https://github.com/Shock-Link/Wiki

nav:
  - Home: index.md
  - Quickstart:
    - quickstart/terminology.md
    - Getting shocked:
      - quickstart/getting-shocked/sourcing-hardware.md
      - quickstart/getting-shocked/choosing-a-server.md
      - quickstart/getting-shocked/create-an-account.md
    - Shocking others:
      - quickstart/shocking-others/create-account.md
  - Hardware:
    - Shockers:
      - hardware/shockers/identifying.md
      - hardware/shockers/buying-guide.md
    - Remotes:
      - hardware/remotes/identifying.md
#      - hardware/remotes/buying-guide.md
    - Boards:
      - 'hardware/boards/pishock-2023.md'
      - 'hardware/boards/pishock-lite-2021.md'
      - 'hardware/boards/pishock-plus-2021.md'
    - Controllers:
      - Do-it-yourself:
        - hardware/diy/prerequisites.md
        - hardware/diy/sourcing-parts.md
        - hardware/diy/assembling.md
      - Second-party vendors:
        - hardware/vendors-second-party/about.md
        - Europe:
          - hardware/vendors-second-party/luc.md
      - Third-party vendors:
        - hardware/vendors-third-party/about.md
        - Pishock:
          - 'hardware/vendors-third-party/pishock/custom-v1.md'
          - 'hardware/vendors-third-party/pishock/lite.md'
          - 'hardware/vendors-third-party/pishock/plus.md'
  - Software:
    - Shockers:
      - software/shockers/caixianlin.md
  - Selfhosting:
    - 'selfhosting/selfhosting.md'
  - Contributing:
    - 'contributing/contributing.md'

theme:
  name: material
  logo: static/branding/Icon.svg
  favicon: static/branding/Icon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags:
      enabled: true
      
extra:
  # Tag definitions for tagging pages.
  tags:
    selfhosting: banana

  # Social links rendered in the footer.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AHcCbXbEcF
      name: Discord

    - icon: fontawesome/brands/github
      link: https://github.com/Shock-Link
      name: GitHub
