site_name: OpenShock
docs_dir: docs
site_url: https://openshock.io/
repo_url: https://github.com/Shock-Link/Wiki

nav:
  - Home: index.md
  - Quickstart:
    - quickstart/terminology.md
    - Getting shocked:
      - quickstart/getting-shocked/sourcing-hardware.md
      - quickstart/getting-shocked/choosing-a-server.md
      - quickstart/getting-shocked/create-an-account.md
    - Shocking others:
      - quickstart/shocking-others/create-account.md
  - Hardware:
    - 'hardware/buy.md'
    - Shockers:
      - hardware/shockers/buying-guide.md
    - Prebuilt controllers:
      - hardware/prebuilt/vendors.md
    - DIY Controller:
      - hardware/diy/prerequisites.md
      - hardware/diy/sourcing-parts.md
      - hardware/diy/building.md
    - Other vendors:
      - Pishock:
        - 'hardware/pishock/custom-v1.md'
        - 'hardware/pishock/lite.md'
        - 'hardware/pishock/plus.md'
  - Selfhosting:
    - 'selfhosting/selfhosting.md'
  - Contributing:
    - 'contributing/contributing.md'

theme:
  name: material
  logo: static/branding/Icon.svg
  favicon: static/branding/Icon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags:
      enabled: true
      
extra:
  # Tag definitions for tagging pages.
  tags:
    selfhosting: banana

  # Social links rendered in the footer.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AHcCbXbEcF
      name: Discord

    - icon: fontawesome/brands/github
      link: https://github.com/Shock-Link
      name: GitHub
