on:
  push:
    branches:
      - master
      - feature/mkdocs

name: ci-master

env:
  SHOCKLINK_API_URL: api.shocklink.net
  SHOCKLINK_FW_VERSION: master-${{ github.sha }}

jobs:

  # Copied verbatim from https://docs.platformio.org/en/stable/integration/ci/github-actions.html
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for mkdocs-git-authors-plugin

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-arch

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install MkDocs
        run: pip install mkdocs-material
